### ISSUE TITLE
Could not compile program with NativeAOT

### ISSUE THREAD

**Issue by Carcass-Project** [dotnet/runtimelab#1659] opened 2021-10-17 20:46 UTC
Hello! I have been trying to compile my Hello, world! application with NativeAOT however I get this error:

```
LINK : fatal error LNK1104: cannot open file '@(NetCoreAppNativeLibrary->'C:\Users\Lia's Mansion\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\6.0.0-rc.1.21420.1\framework\%(Identity)-Static.lib')' [C:\Users\Lias Mansion\source\repos\IL2CPPTests\IL2CPPTests\IL2CPPTests.csproj]
C:\Users\Lia's Mansion\.nuget\packages\microsoft.dotnet.ilcompiler\6.0.0-rc.1.21420.1\build\Microsoft.NETCore.Native.targets(352,5): error MSB3073: The command ""D:\VS2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\link.exe"  @"obj\release\net6.0\win-x64\native\link.rsp"" exited with code 1104. [C:\Users\Lias Mansion\source\repos\IL2CPPTests\IL2CPPTests\IL2CPPTests.csproj]
```

I really have no clue what is going on, but it happens when the DLL file is being made(with dotnet publish -r win-x64 -c Release)

Thanks for any help in advance. :D

**Comment by jkotas** [comment] 2021-10-17 22:08
Could you please share the repro steps and/or shared the verbose build log for the error? To create verbose log, run the build with `/v:d` option. For example, `dotnet publish -r win-x64 -c Release /v:d >log.txt` .

**Comment by Carcass-Project** [comment] 2021-10-18 13:42
[log.txt](https://github.com/dotnet/runtimelab/files/7365355/log.txt)
Here's the log, and to recreate it, I guess just follow the tutorial written on the github page for NativeAOT.

**Comment by jkotas** [comment] 2021-10-19 02:28
Thanks for sharing the log. The problem is triggered by `'` character in your home directory path. #1664 should fix it.

**Comment by MichalStrehovsky** [comment] 2021-10-20 08:20
This should be fixed in the latest package.

**Closed as completed by MichalStrehovsky** 2021-10-20 08:20 UTC
Labels: area-NativeAOT-coreclr
