### ISSUE TITLE
[NativeAOT-LLVM] Compilation failure with async/EH/lock

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2641] opened 2024-08-01 03:09 UTC
The following, distilled from https://github.com/dotnet/runtimelab/blob/53dc49532ac2d8e49c739d784515d66ef0434851/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/BrowserWebSockets/BrowserWebSocket.cs#L316
```c#
public class SafeContext
{
    private static object _lockObject = new object();

    class OperationCanceledException : Exception
    { }

    public static async Task ConnectAsyncCore(CancellationToken cancellationToken)
    {
        Task openTask;

        try
        {
            await Task.CompletedTask;
        }
        catch (OperationCanceledException ex)
        {
            throw;
        }
        catch (Exception)
        {
            lock (_lockObject)
            {
            }
            throw;
        }
    }
}

```

Causes an assert in the LLVM verification
```
    Unwind edges out of a funclet pad must have the same unwind dest
      %225 = catchpad within %224 [ptr null], !dbg !5841
      invoke void @llvm.wasm.rethrow() [ "funclet"(token %225) ]
              to label %BT00.4 unwind label %BT02.1, !dbg !5841
      invoke void @RhpRethrow(ptr %142, ptr %141) [ "funclet"(token %225) ]
              to label %BB15.6 unwind label %BT03.1, !dbg !5849
    Assertion failed: !llvm::verifyFunction(*llvmFunc, &llvm::errs()), file C:\github\runtimelab\src\coreclr\jit\llvmcodegen.cpp, l
  ine 830
    abort() has been called
```
This test is added to the branch, https://github.com/yowl/runtimelab/tree/async-eh, although that is based on the linux CI work, the last commit should be cherry pickable.

cc @SingleAccretion

**Comment by SingleAccretion** [comment] 2024-08-07 18:35
The root cause of this bug is the evidently mistaken assumption that mutually-protecting clauses always come adjoint to each other in the Jit's EH table. In other words, same flavor of a bug as what was fixed in https://github.com/dotnet/runtime/pull/104531.

**Closed as completed** 2024-08-27 17:12 UTC
Labels: area-NativeAOT-LLVM
