### ISSUE TITLE
[ NativeAot ] Sizes are much smaller than there were originally

### ISSUE THREAD

**Issue by FoggyFinder** [dotnet/runtimelab#450] opened 2020-12-12 07:54 UTC
After upgrading all sizes in an app don't match non-coreRt version.

Here is a screen for empty Avalonia app :

![изображение_2020-12-12_094730](https://user-images.githubusercontent.com/16510738/101978630-0cd86500-3c5f-11eb-8d0e-519f5472f048.png)

App from the publish folder is on the right side

Version of packages:

`Avalonia`: 0.10.0-rc1
`microsoft.dotnet.ilcompiler` 6.0.0-alpha.1.20611.2

**Comment by jkotas** [comment] 2020-12-12 18:17
Thank you for reporting this issue! The fix is in #451.

The bug was caused by the runtime incorrectly calling LoadLibraryW instead of LoadLibraryA [here](
https://github.com/AvaloniaUI/Avalonia/blob/2a24c8ff714e05769c71485859faf04cb132f9e1/src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs#L1244).

**Comment by FoggyFinder** [comment] 2020-12-12 18:21
wonderful, thank you

**Closed** 2020-12-14 19:36 UTC
