### ISSUE TITLE
[ NativeAOT ] App closes silently on the latest Avalonia immediately after run

### ISSUE THREAD

**Issue by FoggyFinder** [dotnet/runtimelab#449] opened 2020-12-11 20:39 UTC
Upgraded to the latest `0.10.0-rc1` version of Avalonia. No exception is thrown but my app isn't launched either.
No idea what could it be.

Reproducible on the empty Avalonia app as well.

**Comment by jkotas** [comment] 2020-12-12 01:19
Avalonia depends on zlib compression on startup path now. This is duplicate of https://github.com/dotnet/runtimelab/issues/338. Can you try to apply the workaround at https://github.com/dotnet/runtimelab/issues/338#issuecomment-743577900 ?

(I plan to create a proper fix for this by end of year.)

**Closed** 2020-12-12 01:20 UTC

**Comment by FoggyFinder** [comment] 2020-12-12 07:42
Thank you. It does solve this issue and I was able to run app but the view is now different that it was before. I'll open a new issue.
