### ISSUE TITLE
Install coreRT 

### ISSUE THREAD

**Issue by sangramsalunkhe97** [dotnet/runtimelab#1210] opened 2021-06-08 04:27 UTC
Hi , I am done with building of source code by command `"./build.sh -s clr -c release "` on ubuntu 18.04 for that see the following screenshot. Now i wanna install coreRT for same but not get any idea how to do that. 
![error2](https://user-images.githubusercontent.com/81962828/121020855-678dec00-c7be-11eb-8ad8-e1265e38ade1.png)

**Comment by jkotas** [comment] 2021-06-08 04:34
Duplicate of #1207

Check my reply at https://github.com/dotnet/runtimelab/issues/1207#issuecomment-856017604

**Closed as completed by jkotas** 2021-06-08 04:34 UTC
Labels: question, area-NativeAOT-coreclr
