### ISSUE TITLE
Crash running Avalonia AOT binaries in macOS

### ISSUE THREAD

**Issue by danipen** [dotnet/runtimelab#1053] opened 2021-05-01 12:08 UTC
Hi

I'm trying to build and run AOT binaries for both Windows and macOS platforms. I'm using the the [following Avalonia AOT application example](https://github.com/teobugslayer/AvaloniaCoreRTDemo).

- On **Windows platform** it builds and runs as expected
- On **macOS** (Big Sur 11.2.3), it builds (with a bunch of warnings), but it crashes at runtime.

This is the build output, as you can see the linker outputs a lot of warnings:

```
$ AvaloniaCoreRTDemo$ dotnet publish -r osx-x64 -c release
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AvaloniaCoreRTDemo.csproj (in 1.79 sec).
  GenerateAvaloniaResourcesTask -> Root: /Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src, 4 resources, Output:obj/Release/net5.0/osx-x64//Avalonia/resources
  avares -> name:/AboutWindow.xaml, path: /Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AboutWindow.xaml, size:6946, ItemSpec:AboutWindow.xaml
  avares -> name:/App.xaml, path: /Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/App.xaml, size:405, ItemSpec:App.xaml
  avares -> name:/MainWindow.xaml, path: /Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/MainWindow.xaml, size:1550, ItemSpec:MainWindow.xaml
  avares -> name:/app.ico, path: /Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/app.ico, size:183198, ItemSpec:app.ico
  AvaloniaCoreRTDemo -> /Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/bin/Release/net5.0/osx-x64/AvaloniaCoreRTDemo.dll
  Generating native code
/Users/danipen/.nuget/packages/avalonia/0.10.0/lib/netcoreapp2.0/Avalonia.Base.dll : warning IL9702: Assembly 'Avalonia.Base' produced AOT analysis warnings. [/Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AvaloniaCoreRTDemo.csproj]
/Users/danipen/.nuget/packages/avalonia/0.10.0/lib/netcoreapp2.0/Avalonia.OpenGL.dll : warning IL9702: Assembly 'Avalonia.OpenGL' produced AOT analysis warnings. [/Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AvaloniaCoreRTDemo.csproj]
/Users/danipen/.nuget/packages/avalonia/0.10.0/lib/netcoreapp2.0/Avalonia.MicroCom.dll : warning IL9702: Assembly 'Avalonia.MicroCom' produced AOT analysis warnings. [/Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AvaloniaCoreRTDemo.csproj]
/Users/danipen/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/6.0.0-preview.5.21230.2/framework/System.Linq.Expressions.dll : warning IL9702: Assembly 'System.Linq.Expressions' produced AOT analysis warnings. [/Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AvaloniaCoreRTDemo.csproj]
/Users/danipen/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/6.0.0-preview.5.21230.2/framework/System.ComponentModel.TypeConverter.dll : warning IL9702: Assembly 'System.ComponentModel.TypeConverter' produced AOT analysis warnings. [/Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AvaloniaCoreRTDemo.csproj]
/Users/danipen/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/6.0.0-preview.5.21230.2/sdk/System.Private.CoreLib.dll : warning IL9702: Assembly 'System.Private.CoreLib' produced AOT analysis warnings. [/Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AvaloniaCoreRTDemo.csproj]
/Users/danipen/.nuget/packages/tmds.dbus/0.9.0/lib/netstandard2.0/Tmds.DBus.dll : warning IL9702: Assembly 'Tmds.DBus' produced AOT analysis warnings. [/Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AvaloniaCoreRTDemo.csproj]
/Users/danipen/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/6.0.0-preview.5.21230.2/framework/System.Diagnostics.DiagnosticSource.dll : warning IL9702: Assembly 'System.Diagnostics.DiagnosticSource' produced AOT analysis warnings. [/Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AvaloniaCoreRTDemo.csproj]
/Users/danipen/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/6.0.0-preview.5.21230.2/framework/System.Formats.Asn1.dll : warning IL9702: Assembly 'System.Formats.Asn1' produced AOT analysis warnings. [/Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/AvaloniaCoreRTDemo.csproj]
  ld: warning: could not create compact unwind for _System_Net_Http_System_Net_Http_Headers_QPackStaticTable___cctor: stack subq instruction is too different from dwarf stack size
  ld: warning: could not create compact unwind for _Avalonia_Themes_Default_CompiledAvaloniaXaml__EmbeddedResource__Populate_Avalonia_Themes_Default_ToggleSwitch_xaml: stack subq instruction is too different from dwarf stack size
  ld: warning: could not create compact unwind for _AvaloniaCoreRTDemo_AvaloniaCoreRTDemo_AboutWindow___XamlIlPopulate: stack subq instruction is too different from dwarf stack size
  ld: warning: could not create compact unwind for _S_P_CoreLib_System_Number__Dragon4: stack subq instruction is too different from dwarf stack size
  ld: warning: can't parse dwarf compilation unit info in obj/Release/net5.0/osx-x64/native/AvaloniaCoreRTDemo.o
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_Backtrace' hides a non-existent symbol '__Unwind_Backtrace'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_Backtrace' hides a non-existent symbol '__Unwind_Backtrace'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_DeleteException' hides a non-existent symbol '__Unwind_DeleteException'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_DeleteException' hides a non-existent symbol '__Unwind_DeleteException'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_FindEnclosingFunction' hides a non-existent symbol '__Unwind_FindEnclosingFunction'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_FindEnclosingFunction' hides a non-existent symbol '__Unwind_FindEnclosingFunction'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_Find_FDE' hides a non-existent symbol '__Unwind_Find_FDE'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_Find_FDE' hides a non-existent symbol '__Unwind_Find_FDE'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_ForcedUnwind' hides a non-existent symbol '__Unwind_ForcedUnwind'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_ForcedUnwind' hides a non-existent symbol '__Unwind_ForcedUnwind'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_GetCFA' hides a non-existent symbol '__Unwind_GetCFA'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_GetCFA' hides a non-existent symbol '__Unwind_GetCFA'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_GetDataRelBase' hides a non-existent symbol '__Unwind_GetDataRelBase'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_GetDataRelBase' hides a non-existent symbol '__Unwind_GetDataRelBase'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_GetGR' hides a non-existent symbol '__Unwind_GetGR'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_GetGR' hides a non-existent symbol '__Unwind_GetGR'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_GetIP' hides a non-existent symbol '__Unwind_GetIP'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_GetIP' hides a non-existent symbol '__Unwind_GetIP'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_GetIPInfo' hides a non-existent symbol '__Unwind_GetIPInfo'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_GetIPInfo' hides a non-existent symbol '__Unwind_GetIPInfo'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_GetLanguageSpecificData' hides a non-existent symbol '__Unwind_GetLanguageSpecificData'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_GetLanguageSpecificData' hides a non-existent symbol '__Unwind_GetLanguageSpecificData'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_GetRegionStart' hides a non-existent symbol '__Unwind_GetRegionStart'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_GetRegionStart' hides a non-existent symbol '__Unwind_GetRegionStart'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_GetTextRelBase' hides a non-existent symbol '__Unwind_GetTextRelBase'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_GetTextRelBase' hides a non-existent symbol '__Unwind_GetTextRelBase'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_RaiseException' hides a non-existent symbol '__Unwind_RaiseException'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_RaiseException' hides a non-existent symbol '__Unwind_RaiseException'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_Resume' hides a non-existent symbol '__Unwind_Resume'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_Resume' hides a non-existent symbol '__Unwind_Resume'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_Resume_or_Rethrow' hides a non-existent symbol '__Unwind_Resume_or_Rethrow'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_Resume_or_Rethrow' hides a non-existent symbol '__Unwind_Resume_or_Rethrow'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_SetGR' hides a non-existent symbol '__Unwind_SetGR'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_SetGR' hides a non-existent symbol '__Unwind_SetGR'
  ld: warning: linker symbol '$ld$hide$os10.4$__Unwind_SetIP' hides a non-existent symbol '__Unwind_SetIP'
  ld: warning: linker symbol '$ld$hide$os10.5$__Unwind_SetIP' hides a non-existent symbol '__Unwind_SetIP'
  ld: warning: linker symbol '$ld$hide$os10.4$___deregister_frame' hides a non-existent symbol '___deregister_frame'
  ld: warning: linker symbol '$ld$hide$os10.5$___deregister_frame' hides a non-existent symbol '___deregister_frame'
  ld: warning: linker symbol '$ld$hide$os10.4$___deregister_frame_info' hides a non-existent symbol '___deregister_frame_info'
  ld: warning: linker symbol '$ld$hide$os10.5$___deregister_frame_info' hides a non-existent symbol '___deregister_frame_info'
  ld: warning: linker symbol '$ld$hide$os10.6$___deregister_frame_info' hides a non-existent symbol '___deregister_frame_info'
  ld: warning: linker symbol '$ld$hide$os10.4$___deregister_frame_info_bases' hides a non-existent symbol '___deregister_frame_info_bases'
  ld: warning: linker symbol '$ld$hide$os10.5$___deregister_frame_info_bases' hides a non-existent symbol '___deregister_frame_info_bases'
  ld: warning: linker symbol '$ld$hide$os10.6$___deregister_frame_info_bases' hides a non-existent symbol '___deregister_frame_info_bases'
  ld: warning: linker symbol '$ld$hide$os10.4$___register_frame' hides a non-existent symbol '___register_frame'
  ld: warning: linker symbol '$ld$hide$os10.5$___register_frame' hides a non-existent symbol '___register_frame'
  ld: warning: linker symbol '$ld$hide$os10.4$___register_frame_info' hides a non-existent symbol '___register_frame_info'
  ld: warning: linker symbol '$ld$hide$os10.5$___register_frame_info' hides a non-existent symbol '___register_frame_info'
  ld: warning: linker symbol '$ld$hide$os10.6$___register_frame_info' hides a non-existent symbol '___register_frame_info'
  ld: warning: linker symbol '$ld$hide$os10.4$___register_frame_info_bases' hides a non-existent symbol '___register_frame_info_bases'
  ld: warning: linker symbol '$ld$hide$os10.5$___register_frame_info_bases' hides a non-existent symbol '___register_frame_info_bases'
  ld: warning: linker symbol '$ld$hide$os10.6$___register_frame_info_bases' hides a non-existent symbol '___register_frame_info_bases'
  ld: warning: linker symbol '$ld$hide$os10.4$___register_frame_info_table' hides a non-existent symbol '___register_frame_info_table'
  ld: warning: linker symbol '$ld$hide$os10.5$___register_frame_info_table' hides a non-existent symbol '___register_frame_info_table'
  ld: warning: linker symbol '$ld$hide$os10.6$___register_frame_info_table' hides a non-existent symbol '___register_frame_info_table'
  ld: warning: linker symbol '$ld$hide$os10.4$___register_frame_info_table_bases' hides a non-existent symbol '___register_frame_info_table_bases'
  ld: warning: linker symbol '$ld$hide$os10.5$___register_frame_info_table_bases' hides a non-existent symbol '___register_frame_info_table_bases'
  ld: warning: linker symbol '$ld$hide$os10.6$___register_frame_info_table_bases' hides a non-existent symbol '___register_frame_info_table_bases'
  ld: warning: linker symbol '$ld$hide$os10.4$___register_frame_table' hides a non-existent symbol '___register_frame_table'
  ld: warning: linker symbol '$ld$hide$os10.5$___register_frame_table' hides a non-existent symbol '___register_frame_table'
  ld: warning: linker symbol '$ld$hide$os10.6$___register_frame_table' hides a non-existent symbol '___register_frame_table'
  AvaloniaCoreRTDemo -> /Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/bin/Release/net5.0/osx-x64/publish/
```

And, when running it, the process just **gets aborted**:

```
AvaloniaCoreRTDemo$ /Users/danipen/Documents/GitHub/AvaloniaCoreRTDemo/src/bin/Release/net5.0/osx-x64/publish/AvaloniaCoreRTDemo
[1]    23921 abort
```

**How can I get some information about the crash?** Any help would be appreciated.

**Comment by jkotas** [comment] 2021-05-01 13:27
Run it under lldb:
```
lldb ./AvaloniaCoreRTDemo
r
```
It is crashing for me with:
```
lldb ./AvaloniaCoreRTDemo
(lldb) target create "./AvaloniaCoreRTDemo"
Current executable set to '/Users/jkotas/AvaloniaCoreRTDemo/src/bin/Release/net5.0/osx-x64/publish/AvaloniaCoreRTDemo' (x86_64).
(lldb) r
Process 25485 launched: '/Users/jkotas/AvaloniaCoreRTDemo/src/bin/Release/net5.0/osx-x64/publish/AvaloniaCoreRTDemo' (x86_64)
2021-05-01 06:16:34.494364-0700 AvaloniaCoreRTDemo[25485:156224] Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key 'Avalonia.Native.Interop.IAvaloniaNativeFactory' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey) + 0x54
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey) + 0x50
   at Avalonia.MicroCom.MicroComRuntime.CreateProxyFor[T](IntPtr, Boolean) + 0x41
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(IntPtr, AvaloniaNativePlatformOptions) + 0x35
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(AvaloniaNativePlatformOptions) + 0xcc
   at Avalonia.AvaloniaNativePlatformExtensions.<>c__DisplayClass0_0`1.<UseAvaloniaNative>b__0() + 0x69
   at Avalonia.Controls.AppBuilderBase`1.Setup() + 0xd4
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T, String[], ShutdownMode) + 0x53
   at AvaloniaCoreRTDemo!<BaseAddress>+0xe30ff4
```
The unhandled exception details are sent to stderr and you would just see them even outside debugger in regular console apps. Avalonia or mac UI are redirecting stderr somehow and so you have to run under debugger to see them.

**Comment by jkotas** [comment] 2021-05-01 13:49
This type of error is typically caused by use of reflection that is not compatible with IL trimming. For NativeAOT, it can be worked around by  pinning the required types or assemblies using https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/rd-xml-format.md. Ideally, Avalonia would be fixed to be compatible with IL trimming out of the box by annotating or avoiding its use of reflection.

The IL9702 warnings in the build output are about this. You can get more detailed ones by including `<TrimmerSingleWarn>false</TrimmerSingleWarn>` in the .csproj file.

**Comment by danipen** [comment] 2021-05-01 14:14
Thank you for the detailed information. Quick question. Why it works for win-x64 and it doesn't for macOS?

**Comment by jkotas** [comment] 2021-05-01 14:39
The bad reflection use is probably in macOS specific code.

**Comment by jkotas** [comment] 2021-05-01 14:41
Avalonia switches the implementation based on the OS: https://github.com/AvaloniaUI/Avalonia/blob/7842883961d094e08e9def7f30cf32fd573179c7/src/Avalonia.Desktop/AppBuilderDesktopExtensions.cs#L20-L34 . The crash is in AvaloniaNative that is only used for OSX.

**Comment by kekekeks** [comment] 2021-05-01 22:29
@jkotas our COM layer doesn't use reflection, it registers everything in the module initializer. Could it be that module initializer got removed by IL linker?

**Comment by Suchiman** [comment] 2021-05-02 00:58
@kekekeks more likely the issue is #193

**Comment by jkotas** [comment] 2021-05-02 02:51
If Avalonia depends on module constructors on macOS, then it is likely #193.

**Comment by kekekeks** [comment] 2021-05-02 07:14
Ah, greeeeeat... I guess we need to switch to manual initialization then.

**Comment by jkotas** [comment] 2021-05-02 14:31
Or you can wait for the NativeAOT bug to get fixed. It is not hard to fix. We just have not gotted to it yet.

**Comment by jkotas** [comment] 2021-05-02 14:47
Changing Avalonia to do exclicit initialization that is only done for macOS may be better in this case anyway. Once the module constructor bug is fixed, I expect that the static constructor is going to run even on other OSes with NativeAOT, slowing down startup on other OSes unnecessarily.

**Comment by jkotas** [comment] 2021-07-12 15:08
Duplicate of  #193

**Closed as completed by jkotas** 2021-07-12 15:08 UTC
Labels: area-NativeAOT-coreclr

**Comment by kekekeks** [comment] 2021-07-13 21:25
We'll fix this on Avalonia side by removing the need for module initializers. Sorry for the delay, have been suffering from covid for almost a month already.

**Comment by hez2010** [comment] 2021-09-17 05:35
Module initializers support has been added to the latest NativeAOT compiler. No workaround is needed anymore.
