### ISSUE TITLE
IOT armv6 armv7 AVR ARM32 Zephyr esp32

### ISSUE THREAD

**Issue by rodrigonunes100** [dotnet/runtimelab#1112] opened 2021-05-11 12:14 UTC
NativeAOT official support for armv6 armv7 AVR ARM32 ARDUINO Zephyr esp32 ? It would be sensational.

**Comment by jkotas** [comment] 2021-05-11 12:54
Duplicate of https://github.com/dotnet/runtimelab/issues/833

**Closed as completed by jkotas** 2021-05-11 12:54 UTC
