### ISSUE TITLE
[NativeAOT] wrong path Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) on macOS

### ISSUE THREAD

**Issue by andreakarasho** [dotnet/runtimelab#305] opened 2020-11-05 08:15 UTC
I've a variable:

```csharp
private static readonly string _settings_path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "ClassicUOLauncher", "launcher_settings.xml");
```

and a function `Save`:
```csharp
FileInfo file = new FileInfo(_settings_path);

if (file.Directory != null && !file.Directory.Exists)
{
      file.Directory.Create();
}
// bla bla bla
```
When user hit the `Save` function application crashes with:
```
System.IO.IOException: The file '/Users/{username}/Desktop/ClassicUOLauncher/ClassicUOLauncher' already exists.
   at System.IO.FileSystem.CreateDirectory(String) + 0x53b
   at System.IO.DirectoryInfo.Create() + 0x1b
```

The result of `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)` is: `/Users/{username}/Desktop/ClassicUOLauncher/`
instead it should be: `/Users/{username}/.config` [like linux]

**Comment by jkotas** [comment] 2020-11-05 09:01
Do you see this behavior with NativeAOT runtime only; or do you see this behavior with regular .NET runtime as well? If it is the latter, the issue should be opened in dotnet/runtime repo.

The path returned by `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)` is influenced by the value of `XDG_CONFIG_HOME` environment variable. I suspect that this variable points to `/Users/{username}/Desktop/ClassicUOLauncher` in your situation and that's why you are seeing this behavior.

**Comment by jkotas** [comment] 2020-11-05 09:05
Related: https://github.com/dotnet/runtime/issues/40353

**Comment by jkotas** [comment] 2020-11-18 17:56
Closing as duplicate of https://github.com/dotnet/runtime/issues/40353

**Closed by jkotas** 2020-11-18 17:56 UTC
Labels: area-NativeAOT
