### ISSUE TITLE
[NativeAOT] ModuleInitializer does not work

### ISSUE THREAD

**Issue by andreakarasho** [dotnet/runtimelab#1315] opened 2021-07-12 15:00 UTC
```csharp
using System;
using System.Runtime.CompilerServices;

namespace Test
{
    class Program
    {
        public static int _counter = 0;
            
        
        public static void Main()
        {
            Console.WriteLine($"Hello world {++_counter}");
        }
		
	[ModuleInitializer]
	public static void Init()
	{
	     _counter = 999;
	}
    }
}
```

output:
```
Hello world 1
```

**Comment by jkotas** [comment] 2021-07-12 15:08
Duplicate of  #193

**Closed as completed by jkotas** 2021-07-12 15:08 UTC
