### ISSUE TITLE
winform crash on win7 when using published and compile by windows10 x64

### ISSUE THREAD

**Issue by cwing2019** [dotnet/runtimelab#1434] opened 2021-08-20 09:39 UTC
MessageBox shows:

"Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

COM Interop requires ComWrapper instance registered for marshalling."

following is nugetconfig:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  <add key="dotnet-experimental" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json" />
<add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

and projectfile:

<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <MinimumPlatformVersion>7.0</MinimumPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="6.0.0-rc.1.21419.1" />
  </ItemGroup>

</Project>

**Comment by PathogenDavid** [comment] 2021-08-20 10:36
COM (and by extension WinForms) is not fully supported by Native AOT yet: https://github.com/dotnet/runtimelab/issues/306

**Comment by jkotas** [comment] 2021-08-20 11:16
Duplicate of https://github.com/dotnet/runtimelab/issues/1100 . Take a look at https://github.com/kant2002/WinFormsComInterop/ .

**Closed as completed by jkotas** 2021-08-20 11:16 UTC
