### ISSUE TITLE
[NativeAOT] System.Reflection.MissingMetadataException How do I write rd.xml

### ISSUE THREAD

**Issue by lozn00** [dotnet/runtimelab#2029] opened 2022-10-12 01:58 UTC
```

 Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMLBUFH94CEB", Request id "0HMLBUFH94CEB:00000003": An unhandled exception was thrown by the application.
      System.Reflection.MissingMetadataException: 'System.Text.Json.Serialization.Converters.IEnumerableOfTConverter<System.Collections.Generic.IEnumerable<Swashbuckle.AspNetCore.SwaggerUI.UrlDescriptor>,Swashbuckle.AspNetCore.SwaggerUI.UrlDescriptor>' is missing metadata. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=392859
         at System.Reflection.Runtime.General.TypeUnifier.WithVerifiedTypeHandle(RuntimeConstructedGenericTypeInfo, RuntimeTypeInfo[]) + 0x163
         at System.Reflection.Runtime.General.TypeUnifier.GetConstructedGenericTypeWithTypeHandle(RuntimeTypeInfo, RuntimeTypeInfo[]) + 0x3a
         at System.Reflection.Runtime.TypeInfos.RuntimeTypeInfo.MakeGenericType(Type[]) + 0x41f
         at System.Text.Json.Serialization.Converters.IEnumerableConverterFactory.CreateConverter(Type, JsonSerializerOptions) + 0x1269
         at System.Text.Json.Serialization.JsonConverterFactory.GetConverterInternal(Type, JsonSerializerOptions) + 0x46
         at System.Text.Json.JsonSerializerOptions.GetConverterInternal(Type) + 0x3f1
         at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type, Type, MemberInfo) + 0xff
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.GetConverter(Type, Type, MemberInfo, Type&, JsonSerializerOptions) + 0x73
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.AddProperty(MemberInfo, Type, Type, Boolean, Nullable`1, JsonSerializerOptions) + 0x77
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.CacheMember(Type, Type, MemberInfo, Boolean, Nullable`1, Boolean&, Dictionary`2&) + 0x14f
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type, JsonConverter, Type, JsonSerializerOptions) + 0x55a


```

**Comment by jkotas** [comment] 2022-10-12 02:47
Source generators are the only 100% reliable way to perform Json serialization/deserialization in the presence of trimming or AOT compilation without fallbacks.

I would recommend to switch to System.Text.Json source generator instead of trying to workaround these problems with hand-crafted rdxml.

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-7-0

**Comment by jkotas** [comment] 2022-10-12 02:47
Duplicate of https://github.com/dotnet/runtime/issues/74141 and similar issues.

**Closed as completed by jkotas** 2022-10-12 02:47 UTC

**Comment by lozn00** [comment] 2022-10-12 05:35
@jkotas   This code is from the web core api swagger framework , 
Instead of writing code by hand, I'm trying to encrypt the web core api

**Comment by jkotas** [comment] 2022-10-12 06:20
https://github.com/dotnet/aspnetcore/issues/27384 is the tracking issue to make asp.net compatible with trimming and aot. It really needs to be fixed in asp.net.

**Comment by lozn00** [comment] 2022-10-12 06:27
@jkotas   I am relatively dull, how should I repair it?  Are you saying that there is no solution to the current problem?
 I tried to use.NET 6 and.NET 7 with different errors.

**Comment by jkotas** [comment] 2022-10-12 06:30
Correct, there is no simple solution. 

You can probably work around it by handcrafting rd.xml by trial and error, but I would not recommend doing it. It is very fragile solution.

**Comment by lozn00** [comment] 2022-10-12 06:36
rd.xml  The grammar is so complicated that I don't know how to write it. I try to write many times, still error

```

	<Assembly Name="Swashbuckle.AspNetCore.SwaggerUI" Serialize="Required All" Dynamic="Required All" Activate="Required All" DataContractSerializer="Required All" DataContractJsonSerializer="Required All"  MarshalObject="Required All">
			<!--<Namespace Name="Swashbuckle.AspNetCore.SwaggerUI" Serialize="All" />	"Namespace" is not a supported Runtime Directive.	webapi_mes	EXEC	0	
-->
		<Type Name="Swashbuckle.AspNetCore.SwaggerUI.UrlDescriptor" Dynamic="Required All"/>
			
		</Assembly>	

```
