### ISSUE TITLE
Does NativeAOT LLVM will have a future with WPF?

### ISSUE THREAD

**Issue by ccarlo88** [dotnet/runtimelab#1120] opened 2021-05-13 07:10 UTC
Hello,

I just discovered this NativeAOT LLVM repo yesterday but before putting any consideration on using it for anything serious (mainly because I wasn't able to compile an empty WPF project), does msft has any plans on supporting this for WPF in a long term? If yes, are there a clear roadmap on what is being focused first?

I ask because I got a little bit tired of "propaganda" in recent years, many ideas coming up and they are suddenly dropped, are just half of a solution or when they arrive I will already be retired.

Thank you.

**Comment by En3Tho** [comment] 2021-05-13 07:32
I believe native AOT (non LLVM version) is one of solid goals for sure. Afaik LLVM version does not have this much support. So even if it will be done we can talk .Net 7, not earlier. Just 'AOT' is scheduled for .Net 6. Do you want LLVM version specifically?

**Comment by ccarlo88** [comment] 2021-05-13 07:51
LLVM is cool to make the Linux guys happy but I usually only do software that run on Windows, so it doesn't really need to be LLVM.

So, the native AOT, will it support WPF? I used to develop in UWP and use the native compilation there but sometimes I need flexibility to work with things out of the sandbox.

Oh and by the way, this new AOT, it really compile to machine code? For me this is more important because of the code obfuscation matter.

**Comment by jkotas** [comment] 2021-05-13 13:05
Duplicate of https://github.com/dotnet/runtimelab/issues/770 . See the comment there on what would need to happen in WPF to be compatible with NativeAOT.

> does msft has any plans on supporting this for WPF in a long term?

msft does not have plans on supporting WPF as part of this experimental project. There are no roadmaps and plans set for NativeAOT beyond this experimental project.

**Closed as completed by jkotas** 2021-05-13 13:05 UTC

**Comment by ccarlo88** [comment] 2021-05-13 16:05
> There are no roadmaps and plans set for NativeAOT beyond this experimental project.

@jkotas your answer is really appreciated, thank you! 

I've spent quite a long time creating libraries and software on .NET Standard and some others specially for UWP thinking that Native compilation would continue to be available. As it is not on official roadmap I, as well other thousands of developers, just wasted our time.
It would be nice if MSFT in the future publish more clear information on what are the real and concrete plans for future development, so developers like me don't need to keep waiting for a solution which will never come and are able to move to other development platforms.
