### ISSUE TITLE
Does native AOT work for winforms?

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/runtimelab#432] opened 2020-12-06 19:38 UTC
does this compile winforms down to native win32 apps?

**Comment by jkotas** [comment] 2020-12-06 20:04
It does not. WinForms have quite a bit of COM interop that NativeAOT does not support currently.

Duplicate of https://github.com/dotnet/runtimelab/issues/306

**Closed by jkotas** 2020-12-06 20:04 UTC
