### ISSUE TITLE
NativeAOT webapi use webservice  System.PlatformNotSupportedException: Dynamic code generation is not supported on this platform.

### ISSUE THREAD

**Issue by lozn00** [dotnet/runtimelab#2032] opened 2022-10-12 06:34 UTC
My code uses the webservice code and raises this exception when executing the new ChannelFactory

```
            var binding = new BasicHttpBinding();
            var endpoint = new EndpointAddress($"{LoginDefines.getWebServiceAddress()}");

            var factory = new ChannelFactory<Service1Soap>(binding, endpoint);

            var callClient = factory.CreateChannel();

```

```


Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'webapi_mes.api.login.LoginController.requestLogin (webapi_mes)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "requestLogin", controller = "Login"}. Executing controller action with signature System.String requestLogin(System.String, System.String, System.String, System.String, System.String) on controller webapi_mes.api.login.LoginController (webapi_mes).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action webapi_mes.api.login.LoginController.requestLogin (webapi_mes) in 91.5217ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'webapi_mes.api.login.LoginController.requestLogin (webapi_mes)'
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMLC37MA2B6C", Request id "0HMLC37MA2B6C:00000002": An unhandled exception was thrown by the application.
      System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
       ---> System.PlatformNotSupportedException: Dynamic code generation is not supported on this platform.
         at System.Reflection.Emit.ReflectionEmitThrower.ThrowPlatformNotSupportedException() + 0x43
         at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName, AssemblyBuilderAccess) + 0x16
         at System.Reflection.DispatchProxyGenerator.ProxyAssembly..ctor() + 0x86
         at System.Reflection.DispatchProxyGenerator..cctor() + 0x79
         at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x17c
         --- End of inner exception stack trace ---
         at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x27e
         at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnGCStaticBase(StaticClassConstructionContext*, Object) + 0x1b
         at System.Reflection.DispatchProxyGenerator.GetProxyType(Type, Type) + 0x3c
         at System.Reflection.DispatchProxyGenerator.CreateProxyInstance(Type, Type) + 0x34
         at System.Reflection.DispatchProxy.Create[T, TProxy]() + 0x6e
         at System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy[TChannel](MessageDirection, ServiceChannel) + 0x60
         at System.ServiceModel.Channels.ServiceChannelFactory.CreateProxy[TChannel](MessageDirection, ServiceChannel) + 0xcd
         at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel](EndpointAddress, Uri) + 0x12d
         at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress, Uri) + 0x192
         at System.ServiceModel.ChannelFactory`1.CreateChannel() + 0x69
         at webapi_mes.api.login.LoginController.requestLogin(String, String, String, String, String) + 0x123
         at webapi_mes!<BaseAddress>+0x2f71cab
         at System.InvokeUtils.CallDynamicInvokeMethod(Object, IntPtr, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean) + 0x1ac
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x32
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception) + 0x2c
         at System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow(TargetInvocationException) + 0x2c
         at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame) + 0x26e
         at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame) + 0x69
         at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[]) + 0xac
         at webapi_mes!<BaseAddress>+0x30b236
         at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object, Object[]) + 0x43
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper, ObjectMethodExecutor, Object, Object[]) + 0x49
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync() + 0x11e
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ControllerActionInvoker.State&, ControllerActionInvoker.Scope&, Object&, Boolean&) + 0x89b
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync() + 0x77
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x32
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ControllerActionInvoker.ActionExecutedContextSealed) + 0xa3
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ControllerActionInvoker.State&, ControllerActionInvoker.Scope&, Object&, Boolean&) + 0x9b3
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() + 0x65
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x32
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xe4
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x86
         at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x2e
         at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0x1a
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeFilterPipelineAsync>g__Awaited|20_0>d.MoveNext() + 0xe6
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x32
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xe4
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x86
         at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x2e
         at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0x1a
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext() + 0x33b
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x32
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext() + 0x4ca
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x32
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xe4
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x86



```

**Comment by jkotas** [comment] 2022-11-14 03:32
Duplicate of https://github.com/dotnet/runtime/issues/73136

**Closed as completed by jkotas** 2022-11-14 03:32 UTC
