### ISSUE TITLE
PlatformNotSupportedException was thrown in an asp.net core app

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtimelab#1354] opened 2021-07-24 04:09 UTC
Repro (nightly build .NET 6):

[WebTest.zip](https://github.com/dotnet/runtimelab/files/6871874/WebTest.zip)

```
dotnet publish -c Release -r win-x64
```

It's an asp.net core app created with default template. 

```
Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Reflection.Assembly.GetCallingAssembly() + 0x5e
   at <Program>$.<Main>$(String[]) + 0x1d
   at WebTest!<BaseAddress>+0x9d8cdf
```

It turns out to be `GetCallingAssembly` was not supported in NativeAOT. Is there any solution or workaround to it? Or can `GetCallingAssembly` be made the same with `GetExecutingAssembly` (i.e. assuming all assemblies are being inlined)?

https://github.com/dotnet/aspnetcore/blob/0c5456afe95096db6ac5400cecd3440299b42714/src/DefaultBuilder/src/WebApplication.cs#L89
https://github.com/dotnet/aspnetcore/blob/0c5456afe95096db6ac5400cecd3440299b42714/src/DefaultBuilder/src/WebApplication.cs#L97

UPDATE: I found `Switch.System.Reflection.Assembly.SimulatedCallingAssembly` in source code, I think it should be added to using-nativeaot docs.

**Comment by jkotas** [comment] 2021-07-30 06:08
Duplicate of https://github.com/dotnet/aspnetcore/issues/34838

**Closed as completed by jkotas** 2021-07-30 06:08 UTC
Labels: area-NativeAOT-coreclr

**Comment by hez2010** [comment] 2021-07-30 06:10
Any plan to merge https://github.com/dotnet/runtimelab/pull/1355?

**Comment by jkotas** [comment] 2021-07-30 06:40
Yes, I will get to it.
