### ISSUE TITLE
[NativeAOT] unhandled exception

### ISSUE THREAD

**Issue by andreakarasho** [dotnet/runtimelab#691] opened 2021-02-15 12:15 UTC
Repo: https://github.com/mellinoe/veldrid

Steps:
- clone the repo above
- add the NativeAOT support to NeoDemo project
- cd src
- dotnet publish -r win-x64 -c release

publishing the project "NeoDemo" falls in this issue:

```
Unhandled exception. Unhandled exception. Unhandled exception. ILCompiler.CodeGenerationFailedException: Code generation failed for method '[Vortice.DirectX]Vortice.Interop.Read<MessageSeverity>(native int,MessageSeverity[])'
     at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL)
     at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodCodeNode methodCodeNodeNeedingCode, MethodIL methodIL)
     at ILCompiler.RyuJitCompilation.CompileSingleMethod(CorInfoImpl corInfo, MethodCodeNode methodCodeNodeNeedingCode)
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
  ILCompiler.CodeGenerationFailedException: Code generation failed for method '[Vortice.DirectX]Vortice.Interop.Read<MessageCategory>(native int,MessageCategory[])'
     at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL)
     at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodCodeNode methodCodeNodeNeedingCode, MethodIL methodIL)
     at ILCompiler.RyuJitCompilation.CompileSingleMethod(CorInfoImpl corInfo, MethodCodeNode methodCodeNodeNeedingCode)
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
  ILCompiler.CodeGenerationFailedException: Code generation failed for method '[Vortice.DirectX]Vortice.Interop.Read<MessageId>(native int,MessageId[])'
     at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL)
     at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodCodeNode methodCodeNodeNeedingCode, MethodIL methodIL)
     at ILCompiler.RyuJitCompilation.CompileSingleMethod(CorInfoImpl corInfo, MethodCodeNode methodCodeNodeNeedingCode)
     at System.Threading.ThreadPoolWorkQueue.Dispatch()```

**Comment by jkotas** [comment] 2021-02-16 23:00
This is invalid IL in Vortice.DirectX package. Duplicate of https://github.com/amerkoleci/Vortice.Windows/issues/119. The newer versions of the Vortice.DirectX should have the fix.

**Closed by jkotas** 2021-02-16 23:00 UTC
