### ISSUE TITLE
Make type.Name/type.FullName work in reflection free mode

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtimelab#1019] opened 2021-04-26 07:01 UTC
Maybe this isn't possible (and I haven't dug in) but is it possible to make type.Name/type.FullName work with reflection free mode (which I know is basically impossible to make certain workloads work). There are a bunch of scenarios where knowing the type name is important (not just for logging) but for error messages etc.

If that wasn't possible the other crazy idea I had was to support it only for generic methods:

```C#
Something<T> GetSomething<T>()
{
    return new Something<T>(typeof(T).FullName);
}

var something = Something<MyType>();
```

The AOT compiler could replace this with a constant generated at compile time.

```C#
Something<MyType> GetSomething<MyType>()
{
    return new Something<T>("Namespace.MyType");
}
```

**Comment by MichalStrehovsky** [comment] 2021-04-26 09:41
Yup, these are the "[Reflection APIs that are up for discussion](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/reflection-free-mode.md#reflection-apis-that-are-up-for-discussion)".

For that to be feasible, we should ideally get rid of [System.Private.DisabledReflection](https://github.com/dotnet/runtimelab/tree/ae637c170c8439ccc77b5135ad602f25d1f34206/src/coreclr/nativeaot/System.Private.DisabledReflection/src) and replace it with the real reflection stack where we disable certain codepaths using the .NET 5 feature switches. I don't want to replicate metadata parsing and resolution in System.Private.DisabledReflection.

**Comment by josephmoresena** [comment] 2021-05-02 17:54
typeof(T).ToString() is weird but works and that is really a blessing. If you controlls the code you could manual and maintainable (contradictious?) code which combines typeof(T).ToString() with nameof(class) and static code.

**Comment by jkotas** [comment] 2021-07-15 12:38
Duplicate of dotnet/runtime#67193

**Closed as completed by jkotas** 2021-07-15 12:38 UTC
Labels: area-NativeAOT-coreclr
